### ISSUE TITLE
FYI: selinux enabled: tftp

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#78] opened 2021-05-02 19:15 UTC
I've been working with selinux enabled, in Enforcing mode. It all seems to work ok, with the exception of tftp server. For tftp server I need to give that process permissive mode: `semanage permissive -a tftpd_t`.

I don't think this is a warewulf issue - as tftp is pulled from repo in my case (RHEL8, AArch64), but I thought I would record it here in case others are interested in keeping selinux enabled.

**Comment by tcooper** [comment] 2021-05-02 23:23
It's possible that re-labelling the files that tftpd is serving is sufficient and you could it in enforcing mode. This might need to be done every time the are recreated. I've never tried this but I learned about labelling new files for httpd a long time ago when I tried using selinux way before I learned that virtually every cluster managment tool completely disabled selinux.

**Comment by rhenwood-arm** [comment] 2021-05-03 15:19
Yes. I looked into just changing the file context, but I couldn't get it to 'stick' and my impatience got the better of the situation and I went with the approach I described.

I think there is also going to be a NFS selinux context that will be needed to adjusted for cases where selinux is left enabled, but I haven't got to that yet...

**Comment by gmkurtzer** [comment] 2021-05-12 03:33
I will try and replicate. What OS / host version are you running?

**Comment by rhenwood-arm** [comment] 2021-05-12 21:47
I'm running RHEL8 on my Warewulf primary.

**Comment by gmkurtzer** [comment] 2021-08-20 15:47
Is this still an issue for you? I haven't been able to replicate.

**Comment by gmkurtzer** [comment] 2021-09-01 19:19
Closing as I could not reproduce it. If you (or anyone) finds this again, check the extended attributes of the files with a `ls -lZ /var/lib/tftpboot/*` and reopen this issue.

Thanks!

**Closed by gmkurtzer** 2021-09-01 19:19 UTC
