### ISSUE TITLE
AArch64 seems to requre system overlay image to be compressed.

### ISSUE THREAD

**Issue by rhenwood-arm** [hpcng/warewulf#70] opened 2021-04-22 21:02 UTC
after: `wwctl overlay build -a`

```
# file /var/warewulf/provision/overlays/system/node1.img
node1.img: ASCII cpio archive (SVR4 with no CRC)
```
on boot gives:
```...
[   27.467888] Initramfs unpacking failed: junk in compressed archive
...
```

if I `bzip2 /var/warewulf/provision/overlays/system/node1.img` and give the compressed img the name: `node1.img` everything works as expected.

**Comment by gmkurtzer** [comment] 2021-04-24 22:11
Can others test this? I thought that all subsequent initrds had to be decompressed, but that could absolutely be an incorrect assumption.

**Comment by gmkurtzer** [comment] 2021-04-24 23:20
So what is funny is that I just experienced this as well. It required me to compress all initrd layers for it to work for me too now. Perhaps it has something to do with the `rootfstype=rootfs` kernel arg change. <shrugs>

In either case, this works for me on legacy bios and EFI, so I'm making a patch now.

**Comment by gmkurtzer** [comment] 2021-04-25 19:31
I believe that this is fixed as @yqin just confirmed that this is working for him as well. @rhenwood-arm, can you please confirm and close the issue if it is indeed working for you?

Thanks!

**Comment by gmkurtzer** [comment] 2021-08-20 21:23
I am closing this because I believe it is working for ARM as long as we decompress the kernel by hand (which we should address in documentation).

**Closed by gmkurtzer** 2021-08-20 21:23 UTC
Labels: help wanted
