### ISSUE TITLE
Unit tests not running in CI.

### ISSUE THREAD

**Issue by MatthewHink** [hpcng/warewulf#369] opened 2022-04-07 19:30 UTC
Not sure what happened here, but I can fix this. Doesn't look like I have permissions to fill out the assignees field either.

See here https://github.com/hpcng/warewulf/runs/5874333550?check_suite_focus=true
We are doing `make all` which does not run tests. We may want go vet as well.

**Comment by anderbubble** [comment] 2023-09-13 18:32
@MatthewHink you still up for doing this?

**Comment by mslacken** [comment] 2023-09-29 10:23
This isn't a bug

**Comment by anderbubble** [comment] 2023-09-29 22:15
@mslacken do you mean to say this is intended behavior, or just that it's not a code bug?

**Comment by mslacken** [comment] 2023-10-04 07:13
You made the PR which I merged in which `make all` won't run the tests. So its the intended behavior.

**Closed** 2023-10-16 08:17 UTC
Labels: discuss, build, testing
