### ISSUE TITLE
/etc/udev/rules.d/70-ww4-netname.rules not parsed in wwinit overlay

### ISSUE THREAD

**Issue by blixuga** [hpcng/warewulf#805] opened 2023-05-02 20:06 UTC
### Version of Warewulf
```
wwctl version:   4.4.0-1.git_afcdb21
rpc version: apiPrefix:"rc1" apiVersion:"1" warewulfVersion:"4.4.0-1.git_afcdb21"
```

### Expected behavior

```/var/lib/warewulf/overlays/wwinit/etc/udev/rules.d/70-ww4-netname.rules.ww``` gets parsed and rendered properly

### Actual behavior

```/var/lib/warewulf/overlays/wwinit/etc/udev/rules.d/70-ww4-netname.rules```  is missing the .ww suffix so Warewulf is not rendering it.

### Steps to reproduce this behavior
Look at contents of ```/etc/udev/rules.d/70-ww4-netname.rules``` on any node.

Can see the issue here on github: 
[overlays/wwinit/etc/udev/rules.d](https://github.com/hpcng/warewulf/tree/9ceed466ad9bc1f33fc3bc0f110f58d090c012d0/overlays/wwinit/etc/udev/rules.d)

### What OS/distro are you running

```sh
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"

```

### How did you install Warewulf
RPMS

**Comment by anderbubble** [comment] 2023-05-02 20:47
Duplicate of #724, fixed in #744.

**Closed by anderbubble** 2023-05-02 20:47 UTC
